---

- name: import zprezto setting
  copy:
    src: "{{ shell_zshrs_local }}"
    dest: ~/.zshrc.local

- name: import hub setting
  copy:
    src: "{{ shell_hub }}"
    dest: ~/.config/hub

- name: import netrc
  copy:
    src: "{{ shell_netrc }}"
    dest: ~/.netrc
    mode: 0700
