repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
  - repo: https://github.com/ansible/ansible-lint
    rev: v5.3.1
    hooks:
      - id: ansible-lint