- hosts: localhost
  connection: local
  become: no
  pre_tasks:
  # - debug:
  #     var: ansible_env
  #   tags:
  #     - always
  # - debug: 
  #     var: ansible_facts
  #   tags:
  #     - always
  - set_fact:
      ansible_user: "{{  ansible_env.USER  }}"
      ansible_home: "{{  ansible_env.HOME  }}"
    tags:
      - always
  roles:
    - { role: directories, tags: [directories]}
    - { role: osx-defaults, tags: [osx-defaults]}
    - { role: homebrew, tags: [homebrew]}
    - { role: mas, tags: [mas]}
    # - { role: sublime-text, tags: [sublime-text]}
    # - { role: iterm2, tags: [iterm2]}
    - { role: shell, tags: [shell]}
    - { role: zprezto, tags: [zprezto]}
    - { role: karabiner, tags: [karabiner]}
  vars:
    homebrew_path: /opt/homebrew/bin/brew
