- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  roles:
    - { role: homebrew, tags: [homebrew]}
    - { role: homebrew-cask, tags: [homebrew-cask]}
    - { role: ricty, tags: [ricty]}
    - { role: mas, tags: [mas]}
    - { role: directories, tags: [directories]}
    - { role: sublime-text, tags: [sublime-text]}
    - { role: vagrant, tags: [vagrant]}
    - { role: osx-defaults, tags: [osx-defaults]}
    - { role: iterm2, tags: [iterm2]}
    - { role: revealjs, tags: [revealjs]}
    - { role: shell, tags: [shell]}
    - { role: zprezto, tags: [zprezto]}
    - { role: phpbrew, tags: [phpbrew]}
  vars:
    local_dotfiles_ripository: ''
