---
- name: 'Local | create directory workspace'
  file:
    path: ~/workspace
    state: directory

- file:
    path: ~/workspace/go
    state: directory

- name: 'Local | create directory config'
  file:
    path: ~/.config
    state: directory
