name: Lint ansible files

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Cache installed packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.dev.txt') }}

      - name: Install test dependencies
        run: pip3 install -r requirements.dev.txt

      - name: Lint code
        run: |
          yamllint .
          ansible-lint roles